---
- name: Install packages
  apt:
    pkg:
      - "dovecot-imapd"
      - "dovecot-sieve"
    state: latest
    update_cache: yes
  notify: restart_mail_services

- name: Ensure dovecot sieve directory exists
  file:
    path: '{{ sieve_directory }}'
    state: directory
    recurse: yes
    owner: vmail
    group: vmail

- name: Configure config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: "0644"
  loop:
    - { src: templates/dovecot.conf.j2, dest: /etc/dovecot/dovecot.conf }
    - { src: templates/default.sieve.j2, dest: '{{ sieve_directory }}/default.sieve' }
    - { src: templates/dovecot.pam.j2, dest: /etc/pam.d/dovecot }
  register: dovecot_configs

- name: Compile sieve scripts
  command: sievec {{ sieve_directory }}/default.sieve
  when: dovecot_configs.changed
  notify: restart_mail_services
